### ISSUE TITLE
Possibly superfluous code in article "Managing Data Flow in SwiftUI"?

### ISSUE THREAD

**Issue by dirk68-work** [mecid/mecid.github.io#28]
https://mecid.github.io/2019/07/03/managing-data-flow-in-swiftui/

What does the code 

`struct IndexedCollection` and `extension RandomAccessCollection`

in the last code example do. Was it copied there by accident?

**Comment by mecid** [comment]
Hi @dirk68-fu it is used inside ForEach, we need to to generate indexes and hashable ids.
