### ISSUE TITLE
How do you create the post? 

### ISSUE THREAD

**Issue by alok-dks** [mecid/mecid.github.io#42]
Hi Majid, 
It seem you have very nice setup for blog that is being hosted here on github. 

It seem if I fork the repo I would be able to create the blog website. What I am wondering when are you creating the blog post. Do you create them in some sort of HTML editors. 
I am not very good at HTML or CSS. Even though I like your setup a lot. Creating blog in html would be something that I am not sure yet. 
Currently I do little bit blogging on wordpress with its WYSIWYG editor. 
Please help me to understand how easy or hard it is to create blogpost. 
It is plain html website how does your post are lined chronologically. Do you have to do quite a bit editing. 

I would appreciate if you can spare sometime. Thank you so much. 

Best,
Alok C

**Comment by mecid** [comment]
Hi Alok,

There is _posts folder. You put there markdown files which Jekyll uses to generate a static website.
